# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=1000)),
                ('noteType', models.CharField(choices=[('I', 'Informational'), ('R', 'Release Notes'), ('W', 'Warnings')], max_length=1, verbose_name='Note Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog entry',
                'verbose_name_plural': 'Blog entries',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=30, unique=True, verbose_name='Module Name')),
                ('track', models.CharField(choices=[('OTC', 'Order to Cash'), ('RTP', 'Requisition to Pay'), ('RTR', 'Record to Report'), ('OTH', 'Other')], max_length=3)),
                ('globalLead', models.CharField(max_length=50, verbose_name='Global Lead')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('status', models.CharField(default='Planning', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('velocity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Planning', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rallyNumber', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('longDescription', models.CharField(blank=True, max_length=2000, null=True)),
                ('storyType', models.CharField(default='Enhancement', max_length=20)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('businessValue', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('B', 'Backlog'), ('D', 'Defined'), ('P', 'In-Progress'), ('C', 'Complete'), ('A', 'Accepted')], default='B', max_length=1)),
                ('rallyCreationDate', models.DateTimeField(blank=True, null=True)),
                ('completionDate', models.DateTimeField(blank=True, null=True)),
                ('track', models.CharField(blank=True, max_length=30, null=True)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('stakeholders', models.CharField(blank=True, max_length=255, null=True)),
                ('solutionSize', models.CharField(blank=True, max_length=20, null=True)),
                ('blocked', models.CharField(default='N', max_length=1)),
                ('storyURL', models.CharField(blank=True, max_length=200, null=True)),
                ('blockedReason', models.CharField(blank=True, max_length=512, null=True)),
                ('ready', models.CharField(default='N', max_length=1)),
                ('currentSprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentSprint', to='radabo.Sprint')),
                ('initialSprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initialSprint', to='radabo.Sprint')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module', to='radabo.Module')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release', to='radabo.Release')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='radabo.Session')),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
    ]
