# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-17 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radabo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='rallyCreationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='businessValue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
