# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-22 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radabo', '0003_auto_20160817_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
