# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-29 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radabo', '0004_story_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='ready',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
