# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('velocity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Planning', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rallyNumber', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('businessValue', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('B', 'Backlog'), ('D', 'Defined'), ('P', 'In-Progress'), ('C', 'Complete'), ('A', 'Accepted')], default='B', max_length=1)),
                ('completionDate', models.DateTimeField(blank=True, null=True)),
                ('rallyOID', models.BigIntegerField()),
                ('revHistoryURL', models.CharField(max_length=500)),
                ('currentSprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentSprint', to='metrics.Sprint')),
                ('initialSprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initialSprint', to='metrics.Sprint')),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
    ]
