# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-11 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='releaseName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
