# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_story_releasename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='businessValue',
            field=models.IntegerField(blank=True, choices=[(0, 'IT Research'), (1, 'Nice to Have'), (3, 'Personal Productivity Improvement'), (5, 'Regional Productivity Improvement'), (8, 'Global Productivity Improvement'), (13, 'Impacting Financials, Cash, Revenue or Payments'), (20, 'Compliance')], null=True),
        ),
    ]
