# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20160411_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='module',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='stakeholders',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='track',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
