# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20160412_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='currentSprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentSprint', to='metrics.Sprint'),
        ),
        migrations.AlterField(
            model_name='story',
            name='initialSprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initialSprint', to='metrics.Sprint'),
        ),
    ]
