# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_auto_20160413_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('status', models.CharField(default='Planning', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='releaseName',
        ),
        migrations.AlterField(
            model_name='story',
            name='currentSprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentSprint', to='metrics.Sprint'),
        ),
        migrations.AlterField(
            model_name='story',
            name='initialSprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initialSprint', to='metrics.Sprint'),
        ),
        migrations.AddField(
            model_name='story',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release', to='metrics.Release'),
        ),
    ]
