# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-20 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_auto_20160418_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='solutionSize',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='businessValue',
            field=models.IntegerField(blank=True, choices=[(None, 'Undefined'), (0, 'IT Research'), (1, 'Nice to Have'), (3, 'Personal Productivity Improvement'), (5, 'Regional Productivity Improvement'), (8, 'Global Productivity Improvement'), (13, 'Impacting Financials, Cash, Revenue or Payments'), (20, 'Compliance')], null=True),
        ),
    ]
