# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-03 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_auto_20160420_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='rallyOID',
        ),
        migrations.RemoveField(
            model_name='story',
            name='revHistoryURL',
        ),
    ]
