# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-09 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_auto_20160505_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='projectID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='storyID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
