# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-09 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_auto_20160509_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='projectID',
        ),
        migrations.RemoveField(
            model_name='story',
            name='storyID',
        ),
        migrations.AddField(
            model_name='story',
            name='storyURL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
