# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-11 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_auto_20160509_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='storyType',
            field=models.CharField(default='Enhancement', max_length=20),
        ),
    ]
