# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-13 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0012_story_storytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=30, unique=True)),
                ('track', models.CharField(choices=[('OTC', 'Order to Cash'), ('RTP', 'Requisition to Pay'), ('RTR', 'Record to Report')], max_length=3)),
                ('globalLead', models.CharField(max_length=50)),
            ],
        ),
    ]
