# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0013_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='blocked',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='story',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='track',
            field=models.CharField(choices=[('OTC', 'Order to Cash'), ('RTP', 'Requisition to Pay'), ('RTR', 'Record to Report'), ('OTH', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='session',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
