# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-21 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0014_auto_20160614_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='blockedReason',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='globalLead',
            field=models.CharField(max_length=50, verbose_name='Global Lead'),
        ),
        migrations.AlterField(
            model_name='module',
            name='moduleName',
            field=models.CharField(max_length=30, unique=True, verbose_name='Module Name'),
        ),
    ]
