# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-29 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0016_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog entry', 'verbose_name_plural': 'Blog entries'},
        ),
        migrations.AddField(
            model_name='story',
            name='long_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='noteType',
            field=models.CharField(choices=[('I', 'Informational'), ('R', 'Release Notes'), ('W', 'Warnings')], max_length=1, verbose_name='Note Type'),
        ),
    ]
