# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-29 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0017_auto_20160729_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='long_description',
            new_name='longDescription',
        ),
    ]
